import {BrowserConcept,Icon,Page,Reveal,WebsiteCompletionForm} from "@/components/Site";

export const metadata={title:"Complete Your Website in 48 Hours"};
const qualifier="Your 48-hour completion window begins after your required business information, content and photographs are received.";

export default function Websites(){return <Page>
  <section className="page-intro atmosphere completion-intro"><Reveal><Icon name="globe"/><p className="eyebrow">YOUR PREVIEW → YOUR WEBSITE</p><h1>Complete the website you already received.</h1><p className="lede">Add your real photos, services, phone number and domain. Review the finished version, request your agreed changes, and put it live in 48 hours.</p><p className="expiry-note">Your free preview stays live for 7 days. After that it expires.</p><a className="button" href="#complete">Complete my website <Icon name="arrow"/></a></Reveal></section>
  <section><Reveal><div className="inner-showcase"><BrowserConcept kind="pest"/><div><p className="eyebrow">YOUR COMPLETION FLOW</p><h2>The design is there. Now make every detail yours.</h2><p>Your preview is the starting point—not a promise hidden behind a sales call. You decide whether to complete it.</p><div className="contact-steps"><p><b>01</b>Send your photos and business details (about 15 minutes)</p><p><b>02</b>Review your finished site and request agreed changes</p><p><b>03</b>Approve it for your domain</p></div><p className="qualifier">{qualifier}</p></div></div></Reveal></section>
  <section className="atmosphere"><Reveal><div className="section-head"><div><p className="eyebrow">WHAT YOU RECEIVE</p><h2>Everything needed for a clear, credible business website.</h2></div><p>Your written proposal confirms the exact scope before payment.</p></div><div className="grid-2">{[["phone","Your business on every screen","Your services and contact routes stay easy to use on mobile, tablet and desktop."],["spark","Your real identity","Your approved words, photographs, service details and point of difference replace the demonstration content."],["bolt","Your enquiry route","Your phone number, contact form and calls to action give visitors a clear next step."],["check","Your review and handover","You request agreed changes, approve the result and receive clear ownership and handover terms."]].map(x=><article className="glass-card lift" key={x[1]}><Icon name={x[0] as "spark"}/><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></Reveal></section>
  <section className="expiry-section"><Reveal><p className="eyebrow">AN HONEST SEVEN-DAY WINDOW</p><h2>Your preview is held for you, not kept online forever.</h2><p>Each preview is built individually and reserved for the business it was made for. If you love it, claim it. If not, it quietly disappears after seven days — no calls, no pressure.</p></Reveal></section>
  <section className="pricing"><Reveal><article className="glass-card pricing-card"><p className="eyebrow">ONE CLEAR PROJECT FEE</p><h2>No subscription unless you want ongoing help.</h2><div className="price-slot"><span className="tag">AWAITING-KARAN</span><b>Final pricing figure</b></div><p>You receive a fixed quote for your agreed scope before work begins. Domain, hosting or optional ongoing services are listed separately, never added by surprise.</p></article></Reveal></section>
  <section id="complete" className="completion-form-section atmosphere"><Reveal><div className="section-head"><div><p className="eyebrow">COMPLETE YOUR WEBSITE</p><h2>Send the details that make the preview yours.</h2></div><p>Have your preview link ready. You can share anything else after your first reply.</p></div><WebsiteCompletionForm/></Reveal></section>
</Page>}
