import Link from "next/link";
import {BrowserConcept, DesignedPlaceholder, Footer, Header, Icon, Reveal} from "@/components/Site";

const qualifier="Your 48-hour completion window begins after your business information, content and photographs are received.";
const outcomes=[
  ["phone","Customers find you on their phone","Your services and contact details stay clear on the screen your customers use most."],
  ["bolt","They call instead of scrolling past","A focused route from their question to your phone number or enquiry form makes the next step obvious."],
  ["spark","Your reviews work for you","Your genuine customer feedback can sit where it helps new visitors decide."],
  ["globe","You look ready to compete","Your business gets the considered, professional presence customers expect from the biggest name in town."],
] as const;
const problems=[
  ["Leads lost in WhatsApp chats","A simple lead tracker keeps every enquiry visible, assigned and ready for follow-up."],
  ["Quotes made by hand every night","A quote calculator turns your rules into a faster, consistent starting price."],
  ["Spreadsheets nobody trusts","One focused internal tool gives your team a shared, dependable view."],
  ["Repeat questions eating your day","A customer portal gives people answers and next steps without another message."],
] as const;
const faqs=[
  ["Is my preview really free?","Yes. The preview you received is free to view for seven days. You are not charged for looking at it and there is no obligation to continue."],
  ["What happens after 7 days?","Your preview expires and quietly goes offline. There is no countdown trick and no pressure call. If you want it, complete the website before the seven-day window ends."],
  ["Who owns my website?","Your proposal states the ownership and handover terms clearly, including any third-party tools or licenses, before you pay."],
  ["How do payments work safely?","You receive a written scope, fixed quote and payment stages before work begins. Final pricing is awaiting Karan’s confirmation; nothing is added by surprise."],
  ["Where are you based?","Karan works independently with businesses internationally. Your calls, reviews and delivery can all happen remotely."],
];

export default function Home(){return <><Header/><main>
  <section className="home-hero atmosphere"><div className="dot-grid"/><Reveal className="hero-copy-block"><p className="studio-badge"><span/>You received a website preview from me? Start here.</p><p className="eyebrow">WEBSITES IN 48 HOURS · CUSTOM SOFTWARE MVPS IN 21 DAYS</p><h1>Your new website is already built. Let&apos;s make it yours.</h1><p className="hero-copy">You&apos;ve seen the preview. In 48 hours it can carry your real photos, your services, your phone number and your domain — and start bringing you customers.</p><div className="hero-actions"><Link className="button" href="/websites">Complete my website <Icon name="arrow"/></Link><Link className="button outline" href="#showcase">I&apos;m new here — show me examples</Link></div><p className="expiry-note">Your preview stays live for 7 days. After that it expires.</p></Reveal><div className="hero-visual"><div className="preview-browser"><div className="browser-bar"><i/><i/><i/><span>your-business-preview.com</span></div><DesignedPlaceholder label="Drop the preview screenshot you sent them"/><div className="preview-status"><span>Preview status</span><strong>Active — reserved for 7 days</strong></div></div></div><div className="hero-chips"><span>48-Hour Website Activation</span><span>Fixed One-Time Pricing</span><span>21-Day Software MVPs</span><span>Direct Founder Involvement</span></div></section><div className="trust-bar"><strong>BUILT FOR OWNERS CHECKING THEIR PREVIEW IS LEGIT</strong><span>◇ Clear written scope every project</span><span>◇ Secure invoiced payments</span><span>◇ Live video calls, no ghosting</span></div><section className="qualifier-band"><p>{qualifier}</p></section>
  <div className="marquee" aria-label="Two offers"><div>{Array.from({length:4},()=>["Your website, completed in 48 hours","Your custom software MVP, working in 21 days"]).flat().map((x,i)=><span key={i}>{x}<i>✦</i></span>)}</div></div>

  <section><Reveal><div className="section-head"><div><p className="eyebrow">WHAT YOUR WEBSITE DOES FOR YOU</p><h2>Here is what it does for your business.</h2></div><p>Your website should make it easier for the right customer to trust you, understand you and contact you.</p></div><div className="outcome-grid">{outcomes.map(x=><article className="glass-card lift" key={x[1]}><Icon name={x[0]}/><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></Reveal></section>

  <section className="completion atmosphere" id="how-it-works"><Reveal><div className="section-head"><div><p className="eyebrow">HOW IT BECOMES YOURS</p><h2>Three small steps from preview to your own domain.</h2></div><p>{qualifier}</p></div><div className="completion-steps">{[["01","Send your photos and business details","About 15 minutes to share your services, contact details and preferred images."],["02","Review your finished site","See your information in place and request any agreed changes."],["03","It goes live on your domain","Once you approve it, your finished website is connected within the 48-hour window."]].map(x=><article className="glass-card" key={x[0]}><p className="number">{x[0]}</p><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></Reveal></section>

  <section className="expiry-section"><Reveal><p className="eyebrow">THE 7-DAY WINDOW</p><h2>It&apos;s yours for seven days. Then it expires.</h2><p>Each preview is built individually and kept live for the business it was made for. That reservation lasts seven days, then the preview expires.</p><p className="expiry-statement">If you love it, claim it. If not, it quietly disappears — no calls, no pressure.</p><Link className="button" href="/websites">Complete my website <Icon name="arrow"/></Link></Reveal></section>

  <section className="showcase" id="showcase"><Reveal><div className="section-head"><div><p className="eyebrow">FOR NEW VISITORS</p><h2>See the sites other owners claimed.</h2></div><p>These original coded concepts show the standard clearly. They are demonstrations, not claimed client work.</p></div></Reveal>{([['pest','For a service business','Help local customers understand the problem you solve and ask for a quote.'],['interior','For a visual business','Let your work lead while giving the right client a clear consultation path.'],['moving','For a local business','Make services, service area and the next step easy to find on a phone.']] as const).map((x,i)=><Reveal key={x[0]}><article className={`showcase-row ${i%2?'reverse':''}`}><BrowserConcept kind={x[0]}/><div><span className="sample-pill">Sample concept — demonstration</span><p className="eyebrow">{x[1]}</p><h3>{x[2]}</h3><Link className="text-link" href="/websites">See how yours is completed <Icon name="arrow"/></Link></div></article></Reveal>)}</section>

  <section className="testimonials atmosphere"><Reveal><div className="section-head"><div><p className="eyebrow">TRUST, WITHOUT INVENTION</p><h2>People who trust me with their work.</h2></div><p>The final words remain unpublished until Karan confirms them.</p></div><div className="grid-3">{[["AM","Abinay Mandla"],["S","Saloni","Happy Invites"],["D","Dhivya","Lime Fresh"]].map(x=><article className="glass-card" key={x[1]}><div className="avatar">{x[0]}</div><span className="tag">AWAITING-KARAN</span><blockquote>“Testimonial final wording”</blockquote><b>{x[1]}</b>{x[2]&&<p>{x[2]}</p>}</article>)}</div></Reveal></section>

  <section className="pricing"><Reveal><article className="glass-card pricing-card"><Icon name="spark"/><p className="eyebrow">PRICING CLARITY</p><h2>One clear fee. No monthly subscription.</h2><p>No subscription unless you want ongoing help.</p><div className="price-slot"><span className="tag">AWAITING-KARAN</span><b>Final pricing figure</b></div><ul><li><Icon name="check"/>Your agreed website scope</li><li><Icon name="check"/>Your responsive website build</li><li><Icon name="check"/>Your review and agreed changes</li><li><Icon name="check"/>Your documented handover</li></ul><p>Your fixed quote reflects the agreed scope. Optional ongoing help is discussed separately and never added by surprise.</p><Link className="button" href="/websites">Complete my website <Icon name="arrow"/></Link></article></Reveal></section>

  <section className="software-bridge" id="software"><Reveal><p className="eyebrow">CUSTOM SOFTWARE MVPS IN 21 DAYS</p><h2>Need more than a website? <em>I build software too.</em></h2></Reveal></section>

  <section className="software-home atmosphere"><Reveal><div className="section-head"><div><p className="eyebrow">CUSTOM SOFTWARE MVPS IN 21 DAYS</p><h2>Your daily bottleneck, working software in 21 days.</h2></div><p>You bring the recurring problem. You leave with a focused first version your team can actually use.</p></div><div className="flip-grid">{problems.map(x=><article className="flip-card" key={x[0]} tabIndex={0}><div className="flip-card-inner"><div className="flip-face flip-front"><Icon name="x"/><h3>{x[0]}</h3><span>Hover or tap for the answer</span></div><div className="flip-face flip-back"><Icon name="check"/><h3>Your software answer</h3><p>{x[1]}</p></div></div></article>)}</div><div className="mvp-onboarding"><div><p className="eyebrow">SIMPLE ONBOARDING</p><h3>One call. One scope document. One fixed price.</h3><p>Once your scope and required inputs are agreed, you get a working MVP in your hands in 21 days.</p></div><Link className="button light" href="/software">Tell me your bottleneck <Icon name="arrow"/></Link></div></Reveal></section>

  <section className="faq" id="faq"><Reveal><div className="section-head"><div><p className="eyebrow">YOUR QUESTIONS</p><h2>Questions owners ask before saying yes.</h2></div></div>{faqs.map(x=><details key={x[0]}><summary><span>{x[0]}</span><i>+</i></summary><p>{x[1]}</p></details>)}</Reveal></section>
  <section className="final-cta"><div><p className="eyebrow">YOUR 7-DAY PREVIEW</p><h2>Your website is waiting. Make it yours.</h2><p>If you do not claim it, it simply expires after seven days.</p></div><Link className="button light" href="/websites">Complete my website <Icon name="arrow"/></Link></section>
</main><Footer/></>}
