import Link from "next/link";
import {BrowserConcept, CTA, Footer, Header, Icon, ProcessVisual, Reveal} from "@/components/Site";

const qualifier="48-hour delivery begins after receiving the required business information, content and photographs.";
const faqs=[["Where are you based?","I work independently with businesses internationally. Calls, reviews and delivery can all happen remotely."],["How does payment work?","Payment stages and the full fixed quote are agreed before work begins. Final pricing is awaiting confirmation."],["What if I don’t like the first version?","You review the working site and request agreed changes before launch. The scope and revision process are made clear upfront."],["Who owns the website?","Ownership and handover terms are documented in your proposal, including any third-party tools or licenses."],["What about hosting and my domain?","I can help connect the approved site to a domain and suitable hosting. Provider charges remain separate and transparent."],["Does 48 hours always apply?",qualifier+" Custom software follows a separate timeline."]];
export default function Home(){return <><Header/><main>
<section className="home-hero atmosphere"><div className="dot-grid"/><Reveal className="hero-copy-block"><p className="studio-badge"><span/>Independent studio · Direct founder involvement</p><p className="eyebrow">WEBSITES • SOFTWARE • AUTOMATION</p><h1>Fast Websites for Growing Businesses. Launch Yours in 48 Hours.</h1><p className="hero-copy">From high-converting business websites to custom software and automation, I build digital systems that help businesses launch faster, operate efficiently and win more customers.</p><div className="hero-actions"><Link className="button" href="/websites">Get Your Website <Icon name="arrow"/></Link><Link className="button outline" href="/software">Build Custom Software</Link></div></Reveal><div className="hero-visual"><BrowserConcept kind="pest"/><BrowserConcept kind="interior" small/></div><div className="locked-trust"><strong>48-Hour Website Delivery · Fixed One-Time Pricing · Custom Software · International Experience</strong><span>{qualifier}</span></div></section>
<div className="marquee" aria-label="Capabilities"><div>{["48-Hour Website Delivery","Fixed One-Time Pricing","Custom Software","Automation","International Clients","Mobile-First","SEO Basics Included", "48-Hour Website Delivery","Fixed One-Time Pricing","Custom Software","Automation","International Clients","Mobile-First","SEO Basics Included"].map((x,i)=><span key={i}>{x}<i>✦</i></span>)}</div></div>
<section className="problem"><Reveal><p className="eyebrow">FIRST IMPRESSIONS MOVE FAST</p><h2>Customers judge a business by its website in seconds. A slow or missing site can lose them silently. <em>Launch a credible site fast.</em></h2></Reveal></section>
<section><Reveal><div className="section-head"><div><p className="eyebrow">TWO WAYS TO WORK TOGETHER</p><h2>Start with what your business needs now.</h2></div><p>Focused offers, a clear scope and a direct line to the person doing the work.</p></div><div className="paths"><article className="glass-card lift"><Icon name="globe"/><p className="number">01 / WEBSITES</p><h3>Need a business website? Launch in 48 hours.</h3><p>A focused, credible site built around your real business information — ready for customers on every screen.</p><Link className="text-link" href="/websites">Explore the website service <Icon name="arrow"/></Link></article><article className="glass-card lift dark-card"><Icon name="code"/><p className="number">02 / CUSTOM BUILDS</p><h3>Need something custom? Software, portals, automation, lead tracking.</h3><p>Purpose-built systems for the work generic software cannot handle well.</p><Link className="text-link" href="/software">Explore custom software <Icon name="arrow"/></Link></article></div></Reveal></section>
<section className="showcase atmosphere"><Reveal><div className="section-head"><div><p className="eyebrow">SAMPLE WORK</p><h2>See the kind of sites I build.</h2></div><p>Original coded concepts demonstrate the visual standard without pretending they are client work.</p></div></Reveal>{([["pest","Service website",["Focused service pages","Fast, mobile-first build","Clear enquiry form","48-hour launch after inputs"]],["interior","Portfolio website",["Project-led pages","Editorial visual system","Mobile image layouts","Clear consultation path"]],["moving","Local business website",["Location and service pages","Speed-focused build","Quote enquiry form","Simple handover"]]] as const).map((x,i)=><Reveal key={x[0]}><article className={`showcase-row ${i%2?'reverse':''}`}><BrowserConcept kind={x[0]}/><div><span className="sample-pill">Sample concept</span><p className="eyebrow">{x[1]}</p><h3>{i===0?'Built for trust at first glance.':i===1?'A distinctive home for visual work.':'A clear route from visit to quote.'}</h3><ul>{x[2].map(v=><li key={v}><Icon name="check"/>{v}</li>)}</ul></div></article></Reveal>)}<div className="center"><Link className="button" href="/contact">Get one like this → Start a project</Link></div></section>
<section className="process"><div className="section-head"><div><p className="eyebrow">HOW IT WORKS · 01–04</p><h2>A transparent route from first message to launch.</h2></div></div>{[["Share your business details","Send the essentials: services, audience, content, photographs and goals."],["I build and show you the site","I turn your information into a working site you can see and use."],["You review and request changes","Give clear feedback before anything is launched on your domain."],["Launch on your domain","Once approved, the finished site is connected to your domain."]].map((x,i)=><Reveal key={x[0]}><article className={`process-row ${i%2?'reverse':''}`}><div><p className="number">0{i+1}</p><h3>{x[0]}</h3><p>{x[1]}</p></div><ProcessVisual step={i+1}/></article></Reveal>)}</section>
<section className="speed atmosphere"><Reveal><p className="eyebrow">AN HONEST SPEED COMPARISON</p><h2>Less waiting. No imaginary numbers.</h2><div className="bars"><div><p><b>Typical agency timeline</b><span>weeks–months</span></p><i className="bar agency"/></div><div><p><b>This studio</b><span>48 hours after your info arrives</span></p><i className="bar studio"/></div></div><p className="qualifier">{qualifier}</p></Reveal></section>
<section><Reveal><div className="section-head"><div><p className="eyebrow">CLEAR SCOPE</p><h2>Know what is — and is not — included.</h2></div></div><div className="included"><article className="glass-card"><Icon name="check"/><h3>Included</h3>{["Custom visual design for your business","Responsive mobile and desktop build","Technical SEO basics and metadata","Contact forms and enquiry routes","Basic analytics setup"].map(x=><p key={x}><Icon name="check"/>{x}</p>)}</article><article className="glass-card not"><Icon name="x"/><h3>Not included by default</h3>{["Content writing beyond the information you provide","Paid advertising or campaign management","Guaranteed search rankings","Unspecified custom software features","Domain and third-party service fees"].map(x=><p key={x}><Icon name="x"/>{x}</p>)}</article></div></Reveal></section>
<section className="testimonials atmosphere"><Reveal><div className="section-head"><div><p className="eyebrow">CLIENT WORDS</p><h2>Three voices, pending final wording confirmation.</h2></div></div><div className="grid-3">{[["AM","Abinay Mandla"],["S","Saloni","Happy Invites"],["D","Dhivya","Lime Fresh"]].map(x=><article className="glass-card" key={x[1]}><div className="avatar">{x[0]}</div><span className="tag">AWAITING-KARAN</span><blockquote>“Testimonial final wording”</blockquote><b>{x[1]}</b>{x[2]&&<p>{x[2]}</p>}</article>)}</div></Reveal></section>
<section className="pricing"><Reveal><article className="glass-card pricing-card"><Icon name="spark"/><p className="eyebrow">SIMPLE COMMERCIALS</p><h2>One clear project fee. No compulsory subscription.</h2><div className="price-slot"><span className="tag">AWAITING-KARAN</span><b>Final pricing figure</b></div><ul><li><Icon name="check"/>Agreed project scope</li><li><Icon name="check"/>Responsive website build</li><li><Icon name="check"/>Review and agreed changes</li><li><Icon name="check"/>Transparent handover</li></ul><p>Your final quote will reflect the agreed scope. Optional ongoing services are discussed separately, never bundled in by surprise.</p><Link className="button" href="/contact">Request your fixed quote <Icon name="arrow"/></Link></article></Reveal></section>
<section className="faq"><Reveal><div className="section-head"><div><p className="eyebrow">COMMON QUESTIONS</p><h2>Useful answers before we speak.</h2></div></div>{faqs.map(x=><details key={x[0]}><summary><span>{x[0]}</span><i>+</i></summary><p>{x[1]}</p></details>)}</Reveal></section><CTA/></main><Footer/></>}
