import Link from "next/link";
import {Icon,Page,Reveal} from "@/components/Site";

export const metadata={title:"Custom Software MVPs in 21 Days"};
const solutions=[
  ["Leads disappear between chats","Your lead tracker keeps every enquiry, owner and next action in one view."],
  ["Quotes consume every evening","Your quote calculator applies the rules you already use and creates a consistent starting point."],
  ["Customers ask the same questions","Your customer portal puts updates, documents and common answers in one place."],
  ["Bookings require endless messages","Your booking portal gives customers available options and gives your team a shared schedule."],
] as const;
export default function Software(){return <Page>
  <section className="page-intro atmosphere"><Reveal><Icon name="code"/><p className="eyebrow">CUSTOM SOFTWARE MVPS IN 21 DAYS</p><h1>Your daily bottleneck can become a working tool.</h1><p className="lede">Bring the repetitive task, unreliable spreadsheet or scattered customer journey that slows your business down. Get a focused MVP your team can use in 21 days.</p><Link className="button" href="/contact">Tell me your bottleneck <Icon name="arrow"/></Link></Reveal></section>
  <section><Reveal><div className="section-head"><div><p className="eyebrow">FROM PROBLEM TO USEFUL FIRST VERSION</p><h2>Start with the part of your day you want back.</h2></div><p>No invented efficiency claims. Your MVP is scoped around a real workflow you identify.</p></div><div className="problem-flips">{solutions.map((x,i)=><article className="glass-card" key={x[0]}><p className="number">0{i+1} / YOUR PROBLEM</p><h3>{x[0]}</h3><div className="solution-line"><Icon name="arrow"/><p><b>Your software answer</b>{x[1]}</p></div></article>)}</div></Reveal></section>
  <section className="atmosphere"><Reveal><div className="section-head"><div><p className="eyebrow">EXAMPLES, NOT FAKE CASE STUDIES</p><h2>Your MVP might look like this.</h2></div><p>These are generic examples of buildable first versions. They are not claims about past clients or results.</p></div><div className="grid-2">{[["globe","Booking portal","Let customers choose from your available services or times while your team sees one schedule."],["spark","Quote calculator","Turn your existing pricing logic into a guided quote or estimate flow."],["layers","Lead tracker","Keep enquiries, notes, owners and next actions together without an oversized CRM."],["code","Customer portal","Give customers a secure place for updates, documents, requests or repeat actions."]].map(x=><article className="glass-card lift" key={x[1]}><Icon name={x[0] as "code"}/><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></Reveal></section>
  <section><Reveal><div className="section-head"><div><p className="eyebrow">SIMPLE ONBOARDING</p><h2>A short path to a usable MVP.</h2></div><p>The 21-day build window begins after your scope, required access and inputs are agreed and received.</p></div><div className="completion-steps">{[["01","One call","Show the bottleneck, who encounters it and what a useful outcome looks like."],["02","One scope document","See the smallest useful version, boundaries, fixed price and required inputs in writing."],["03","A working MVP in 21 days","Review a working first version built around the scope you approved."]].map(x=><article className="glass-card" key={x[0]}><p className="number">{x[0]}</p><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><div className="center section-action"><Link className="button" href="/contact">Tell me your bottleneck <Icon name="arrow"/></Link></div></Reveal></section>
  <section className="final-cta"><div><p className="eyebrow">YOUR WORKING MVP</p><h2>Put the recurring problem on the table.</h2><p>One call, one scope document and one fixed price before your build begins.</p></div><Link className="button light" href="/contact">Tell me your bottleneck <Icon name="arrow"/></Link></section>
</Page>}
